### ISSUE TITLE
Minimal example not working on CircuitPython 8

### ISSUE THREAD

**Issue by Moving-Electrons** [dupontgu/person-sensor-circuitpython#1]
Followed the basic usage guidelines in the repository. However, after trying to run the file `code.py` on `examples/minimal/`, the following error is triggered:

```
code.py output:
Traceback (most recent call last):
  File "code.py", line 13, in <module>
  File "/lib/person_sensor.py", line 138, in get_faces
RuntimeError: buffer too small

Code done running.

```

Tested on both **Adafruit Feather STM32F405** and **UM FeatherS2** with same results. 
OS: CircuitPython 8.0.3
Person Sensor Ver 1.0

**Comment by dupontgu** [comment]
Thanks for reporting! I've tested on earlier versions of 8, but not on any STM32 hardware. Will try both of those things as soon as I get a chance.

**Comment by Moving-Electrons** [comment]
No problem. I also updated the initial comment to include another board I tried the code on with exactly the same result.

**Comment by dupontgu** [comment]
Thanks - can I also ask which version of the Person Sensor you have? I'm wondering if something in the firmware changed. I actually just got a new one in so I'll test that too.

**Comment by Moving-Electrons** [comment]
Sure, it's ver 1.0. I added it to the initial post.

**Comment by dupontgu** [comment]
Unfortunately I am unable to repro at all. I got an STM32F405 Feather and tried on CircuitPython 8.0.3 and 8.0.4, and it all seems to be working for me, detecting at least 3 faces. Is it possible that any values got changed from the minimal example - or do you have any other code running that may be preventing the library from allocating enough buffer space? I wish I had more to offer. Have you tried your Person Sensor outside of a CircuitPython context?

**Comment by Moving-Electrons** [comment]
Hi, 
Seems this is related to a faulty Person Sensor. I got my hands on another one and the script runs without any issues. Hopefully this is not a widespread thing.

**Comment by petewarden** [comment]
Thanks for the update! I just tried to reproduce this on the FeatherS2 and also didn't experience the problem, so I'm guessing it must be an issue with the sensor itself. I'd be happy to replace the faulty one, just drop me an email - pete@usefulsensors.com
